// JobRadar 公司数据
// 聚焦"隐形好公司"——有融资、有壁垒、但不一定知名

const COMPANIES = [
  // ===== 前沿技术 =====
  {
    id: 1,
    name: "月之暗面 (Moonshot AI)",
    industry: "前沿技术",
    funding: "B轮",
    year: 2023,
    advantage: ["独角兽"],
    location: "北京市",
    media: true,
    hiring: true,
    recruitment: "校招",
    bestEmployer: true,
    desc: "杨植麟创立的大模型公司，Kimi Chat 爆火，阿里/红杉重注。AGI 赛道最受瞩目的创业公司之一，技术氛围极强。",
    fundingAmt: "超10亿美元",
    investors: "阿里巴巴、红杉中国、砺思资本",
    employees: "300-500人",
    product: "Kimi Chat",
    cities: ["北京", "上海", "深圳"],
    techStack: ["Python", "PyTorch", "CUDA", "Go", "React"],
    benefits: ["六险一金", "弹性工作", "期权激励", "免费三餐"],
    website: "https://www.moonshot.cn",
    jobs: [
      { title: "大模型算法工程师", salary: "50-100K", exp: "3-5年", degree: "本科" },
      { title: "后端开发工程师", salary: "35-60K", exp: "3-5年", degree: "本科" },
      { title: "产品经理 (AI方向)", salary: "30-50K", exp: "3-5年", degree: "本科" },
      { title: "产品运营", salary: "25-40K", exp: "2-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "30-50K", exp: "3-5年", degree: "本科" },
      { title: "测试开发工程师", salary: "25-45K", exp: "2-5年", degree: "本科" },
    ]
  },
  {
    id: 2,
    name: "智谱AI (Zhipu AI)",
    industry: "前沿技术",
    funding: "C轮",
    year: 2019,
    advantage: ["独角兽", "高新技术企业"],
    location: "北京市",
    media: true,
    hiring: true,
    recruitment: "校招",
    bestEmployer: true,
    desc: "清华系大模型公司，GLM 系列模型，B端落地扎实。已获北京市人工智能产业投资基金等国资支持，商业化路径清晰。",
    fundingAmt: "超25亿人民币",
    investors: "君联资本、启明创投、北京市AI产业基金",
    employees: "1000+",
    product: "GLM大模型 / ChatGLM",
    cities: ["北京", "上海"],
    techStack: ["Python", "PyTorch", "C++", "CUDA", "K8s"],
    benefits: ["六险一金", "年终奖", "论文发表支持", "北京户口指标"],
    website: "https://www.zhipuai.cn",
    jobs: [
      { title: "NLP算法研究员", salary: "40-80K", exp: "1-3年", degree: "本科" },
      { title: "前端开发工程师", salary: "25-45K", exp: "1-3年", degree: "本科" },
      { title: "AI应用开发工程师", salary: "30-55K", exp: "2-5年", degree: "本科" },
      { title: "AI产品经理", salary: "30-50K", exp: "3-5年", degree: "本科" },
      { title: "后端开发(Go)", salary: "28-48K", exp: "2-5年", degree: "本科" },
      { title: "深度学习研究员", salary: "45-85K", exp: "博士", degree: "博士" },
    ]
  },

  // ===== 企业服务 =====
  {
    id: 3,
    name: "蓝湖 (Lanhu)",
    industry: "企业服务",
    funding: "C轮",
    year: 2017,
    advantage: ["瞪羚企业", "高新技术企业"],
    location: "北京市",
    media: true,
    hiring: true,
    recruitment: "社招",
    bestEmployer: true,
    desc: "产品设计协作平台，已服务超百万设计师和产品经理。从设计稿到代码一站式协作，在国内设计工具赛道稳居头部。",
    fundingAmt: "10亿+人民币",
    investors: "GGV纪源资本、红杉中国、金沙江创投",
    employees: "500-800人",
    product: "蓝湖设计协作平台",
    cities: ["北京", "深圳"],
    techStack: ["React", "TypeScript", "Go", "Node.js", "PostgreSQL"],
    benefits: ["六险一金", "弹性工作", "MacBook Pro", "年度旅游"],
    website: "https://lanhuapp.com",
    jobs: [
      { title: "前端架构师", salary: "40-60K", exp: "5-10年", degree: "本科" },
      { title: "产品经理", salary: "28-45K", exp: "3-5年", degree: "本科" },
      { title: "后端开发 (Go)", salary: "30-50K", exp: "2-5年", degree: "本科" },
      { title: "UI/UX设计师", salary: "22-38K", exp: "2-5年", degree: "本科" },
      { title: "后端开发(Node.js)", salary: "28-45K", exp: "3-5年", degree: "本科" },
      { title: "测试工程师", salary: "20-35K", exp: "2-5年", degree: "本科" },
    ]
  },
  {
    id: 4,
    name: "ShowMeBug",
    industry: "企业服务",
    funding: "A+轮",
    year: 2019,
    advantage: ["高新技术企业"],
    location: "广东省",
    media: false,
    hiring: true,
    recruitment: "社招",
    bestEmployer: true,
    desc: "技术人才评估平台，用实战编程替代传统笔面试。已服务字节、腾讯等数千家企业，技术面试 SaaS 赛道头部玩家。",
    fundingAmt: "近亿元人民币",
    investors: "红杉中国、高瓴创投",
    employees: "100-200人",
    product: "ShowMeBug 技术评估",
    cities: ["深圳", "广州"],
    techStack: ["Ruby", "Rails", "React", "Docker", "AWS"],
    benefits: ["五险一金", "远程办公", "技术书籍报销"],
    website: "https://www.showmebug.com",
    jobs: [
      { title: "全栈工程师", salary: "25-40K", exp: "3-5年", degree: "本科" },
      { title: "技术销售", salary: "20-35K", exp: "2-5年", degree: "本科" },
      { title: "测试开发", salary: "20-35K", exp: "2-5年", degree: "本科" },
      { title: "产品经理", salary: "25-40K", exp: "3-5年", degree: "本科" },
      { title: "前端开发(React)", salary: "22-38K", exp: "2-5年", degree: "本科" },
      { title: "运维工程师", salary: "20-35K", exp: "2-5年", degree: "大专" },
    ]
  },

  // ===== 医疗健康 =====
  {
    id: 5,
    name: "深睿医疗 (DeepWise)",
    industry: "医疗健康",
    funding: "C+轮",
    year: 2017,
    advantage: ["专精特新", "高新技术企业"],
    location: "北京市",
    media: true,
    hiring: true,
    recruitment: "社招",
    bestEmployer: true,
    desc: "AI 医疗影像诊断平台，覆盖肺部、乳腺、脑卒中等多部位。已有 NMPA 三类证，产品落地数百家医院。",
    fundingAmt: "数亿元人民币",
    investors: "君联资本、联想之星、丹华资本",
    employees: "300-500人",
    product: "DeepWise AI影像平台",
    cities: ["北京", "上海"],
    techStack: ["Python", "PyTorch", "C++", "CUDA", "Docker"],
    benefits: ["六险一金", "人才公寓", "专利奖金"],
    website: "https://www.deepwise.com",
    jobs: [
      { title: "医学图像算法工程师", salary: "35-60K", exp: "2-5年", degree: "本科" },
      { title: "Java后端开发", salary: "25-40K", exp: "3-5年", degree: "本科" },
      { title: "临床产品经理", salary: "25-40K", exp: "3-5年", degree: "本科" },
      { title: "Java后端开发", salary: "28-45K", exp: "3-5年", degree: "本科" },
      { title: "前端开发", salary: "22-38K", exp: "2-5年", degree: "本科" },
      { title: "临床数据分析师", salary: "20-35K", exp: "1-3年", degree: "本科" },
    ]
  },

  // ===== 消费电商 =====
  {
    id: 6,
    name: "远方好物",
    industry: "消费电商",
    funding: "A轮",
    year: 2021,
    advantage: ["创新型中小企业"],
    location: "浙江省",
    media: false,
    hiring: true,
    recruitment: "社招",
    bestEmployer: true,
    desc: "优质食品私域电商平台，主打溯源+高品质食品。社交电商新锐，月GMV破亿，团队小而精悍。",
    fundingAmt: "千万级人民币",
    investors: "顺为资本、真格基金",
    employees: "50-100人",
    product: "远方好物私域电商",
    cities: ["杭州"],
    techStack: ["Java", "Spring", "Vue", "MySQL", "Redis"],
    benefits: ["五险一金", "员工内购", "年终分红"],
    website: "https://www.yuanfang.com",
    jobs: [
      { title: "运营总监", salary: "25-40K", exp: "5-10年", degree: "本科" },
      { title: "前端开发", salary: "18-30K", exp: "1-3年", degree: "本科" },
      { title: "内容运营", salary: "12-20K", exp: "1-3年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 先进制造 =====
  {
    id: 7,
    name: "梅卡曼德 (Mech-Mind)",
    industry: "先进制造",
    funding: "C+轮",
    year: 2016,
    advantage: ["专精特新小巨人", "独角兽", "高新技术企业"],
    location: "北京市",
    media: true,
    hiring: true,
    recruitment: "社招",
    bestEmployer: true,
    desc: "工业机器人 3D 视觉引导，已落地汽车、物流、家电等场景。全球领先的 AI+工业机器人公司，出海进展快。",
    fundingAmt: "超15亿人民币",
    investors: "美团、IDG资本、红杉中国",
    employees: "500-800人",
    product: "Mech-Eye 3D视觉",
    cities: ["北京", "上海", "深圳", "慕尼黑", "东京"],
    techStack: ["C++", "Python", "OpenCV", "CUDA", "ROS"],
    benefits: ["六险一金", "海外轮岗", "技术专利奖", "股权激励"],
    website: "https://www.mech-mind.com",
    jobs: [
      { title: "3D视觉算法工程师", salary: "40-70K", exp: "2-5年", degree: "本科" },
      { title: "ROS开发工程师", salary: "30-50K", exp: "2-5年", degree: "本科" },
      { title: "海外销售经理", salary: "25-45K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 教育 =====
  {
    id: 8,
    name: "小鹅通",
    industry: "教育",
    funding: "B轮",
    year: 2016,
    advantage: ["高新技术企业", "瞪羚企业"],
    location: "广东省",
    media: false,
    hiring: true,
    recruitment: "社招",
    bestEmployer: true,
    desc: "知识产品与用户服务 SaaS，服务数百万知识创作者。从知识付费到企业培训，品牌认知度高，盈利稳定。",
    fundingAmt: "数亿元人民币",
    investors: "腾讯、IDG资本",
    employees: "500-1000人",
    product: "小鹅通知识付费SaaS",
    cities: ["深圳", "广州"],
    techStack: ["Java", "Spring Cloud", "Vue", "MySQL", "K8s"],
    benefits: ["五险一金", "年终1-4月", "技术大会报销"],
    website: "https://www.xiaoe-tech.com",
    jobs: [
      { title: "高级Java开发", salary: "30-45K", exp: "5-10年", degree: "本科" },
      { title: "前端开发", salary: "22-38K", exp: "3-5年", degree: "本科" },
      { title: "客户成功经理", salary: "18-28K", exp: "2-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 跨境出海 =====
  {
    id: 9,
    name: "店匠科技 (Shoplazza)",
    industry: "跨境出海",
    funding: "C轮",
    year: 2017,
    advantage: ["高新技术企业", "瞪羚企业"],
    location: "广东省",
    media: true,
    hiring: true,
    recruitment: "社招",
    bestEmployer: true,
    desc: "跨境电商独立站 SaaS，服务全球超 30 万商家。对标 Shopify，专注品牌出海，海外市场增速迅猛。",
    fundingAmt: "超1.5亿美元",
    investors: "软银愿景基金、红杉中国、前海母基金",
    employees: "500-1000人",
    product: "Shoplazza独立站",
    cities: ["深圳", "广州", "新加坡"],
    techStack: ["React", "Node.js", "Go", "TypeScript", "AWS"],
    benefits: ["六险一金", "海外出差", "弹性工作", "英语培训"],
    website: "https://www.shoplazza.com",
    jobs: [
      { title: "前端架构师 (React)", salary: "35-55K", exp: "5-10年", degree: "本科" },
      { title: "后端开发 (Node.js/Go)", salary: "28-45K", exp: "3-5年", degree: "本科" },
      { title: "SEO/增长运营", salary: "20-35K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 体育游戏 =====
  {
    id: 10,
    name: "鹰角网络 (Hypergryph)",
    industry: "体育游戏",
    funding: "战略融资",
    year: 2017,
    advantage: ["独角兽"],
    location: "上海市",
    media: true,
    hiring: true,
    recruitment: "校招",
    bestEmployer: true,
    desc: "明日方舟开发商，二次元游戏 Top 级厂商。单款产品年流水数十亿，研发实力强，新作备受期待。",
    fundingAmt: "未披露",
    investors: "腾讯、B站",
    employees: "500-1000人",
    product: "明日方舟",
    cities: ["上海"],
    techStack: ["C++", "Unity", "Go", "Python", "Unreal"],
    benefits: ["六险一金", "16薪", "项目分红", "免费猫粮（公司有猫）"],
    website: "https://www.hypergryph.com",
    jobs: [
      { title: "游戏服务器开发", salary: "30-50K", exp: "3-5年", degree: "本科" },
      { title: "Unity客户端开发", salary: "28-48K", exp: "3-5年", degree: "本科" },
      { title: "技术美术 (TA)", salary: "30-55K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 智能硬件 =====
  {
    id: 11,
    name: "追觅科技 (Dreame)",
    industry: "智能硬件",
    funding: "C+轮",
    year: 2017,
    advantage: ["独角兽", "高新技术企业"],
    location: "江苏省",
    media: true,
    hiring: true,
    recruitment: "校招",
    bestEmployer: true,
    desc: "智能清洁家电，扫地机器人/洗地机/吸尘器。全球出货量快速增长，技术与性价比双领先，海外市场爆发。",
    fundingAmt: "超36亿人民币",
    investors: "华兴新经济基金、CPE源峰、碧桂园创投",
    employees: "2000+",
    product: "追觅扫地机器人",
    cities: ["苏州", "上海", "深圳", "慕尼黑"],
    techStack: ["C++", "Python", "ROS", "嵌入式C", "SLAM"],
    benefits: ["六险一金", "人才公寓", "海外轮岗", "产品内购"],
    website: "https://www.dreame.com",
    jobs: [
      { title: "嵌入式开发工程师", salary: "28-45K", exp: "3-5年", degree: "本科" },
      { title: "SLAM算法工程师", salary: "35-60K", exp: "2-5年", degree: "本科" },
      { title: "海外电商运营", salary: "20-35K", exp: "2-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 金融 =====
  {
    id: 12,
    name: "XTransfer",
    industry: "金融",
    funding: "D轮",
    year: 2017,
    advantage: ["独角兽", "高新技术企业"],
    location: "上海市",
    media: true,
    hiring: true,
    recruitment: "社招",
    bestEmployer: true,
    desc: "一站式外贸企业跨境金融和风控服务，帮助中小外贸企业解决收款难题。已服务超 30 万家外贸企业。",
    fundingAmt: "超3亿美元",
    investors: "D1 Capital Partners、Telstra Ventures、招商局创投",
    employees: "1000-2000人",
    product: "XTransfer外贸收款",
    cities: ["上海", "深圳", "香港"],
    techStack: ["Java", "Spring", "React", "Flink", "K8s"],
    benefits: ["六险一金", "弹性工作", "补充公积金", "期权"],
    website: "https://www.xtransfer.com",
    jobs: [
      { title: "Java架构师", salary: "40-65K", exp: "5-10年", degree: "本科" },
      { title: "风控算法工程师", salary: "35-55K", exp: "3-5年", degree: "本科" },
      { title: "前端开发", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 本地生活 =====
  {
    id: 13,
    name: "锅圈食汇",
    industry: "本地生活",
    funding: "D+轮",
    year: 2017,
    advantage: ["独角兽"],
    location: "上海市",
    media: true,
    hiring: true,
    recruitment: "社招",
    bestEmployer: true,
    desc: "火锅烧烤食材超市，全国门店超万。从供应链到终端门店全链路打通，下沉市场扩张迅猛。",
    fundingAmt: "超30亿人民币",
    investors: "IDG资本、招银国际、茅台基金",
    employees: "3000+",
    product: "锅圈食汇门店",
    cities: ["上海", "郑州", "成都"],
    techStack: ["Java", "Vue", "Python", "Hadoop", "MySQL"],
    benefits: ["五险一金", "餐补", "内部员工折扣"],
    website: "https://www.guoquan.com",
    jobs: [
      { title: "供应链产品经理", salary: "25-40K", exp: "3-5年", degree: "本科" },
      { title: "数据开发工程师", salary: "28-45K", exp: "3-5年", degree: "本科" },
      { title: "区域运营经理", salary: "20-35K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 汽车出行 =====
  {
    id: 14,
    name: "禾赛科技 (Hesai)",
    industry: "汽车出行",
    funding: "已上市",
    year: 2014,
    advantage: ["高新技术企业"],
    location: "上海市",
    media: true,
    hiring: true,
    recruitment: "校招",
    bestEmployer: true,
    desc: "全球领先的激光雷达制造商，已在美国纳斯达克上市。理想、小米、美团等头部客户，自动驾驶核心供应商。",
    fundingAmt: "IPO 融资1.9亿美元",
    investors: "百度、小米、博世、美团",
    employees: "1000+",
    product: "禾赛激光雷达",
    cities: ["上海", "硅谷", "斯图加特"],
    techStack: ["C++", "Python", "FPGA", "嵌入式Linux", "ROS"],
    benefits: ["六险一金", "股票期权", "海外轮岗", "博士优先落户"],
    website: "https://www.hesaitech.com",
    jobs: [
      { title: "光学工程师", salary: "30-50K", exp: "3-5年", degree: "本科" },
      { title: "嵌入式软件工程师", salary: "28-48K", exp: "3-5年", degree: "本科" },
      { title: "FPGA开发工程师", salary: "35-55K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 通信/半导体 =====
  {
    id: 15,
    name: "此芯科技 (Cix Technology)",
    industry: "通信/半导体",
    funding: "B+轮",
    year: 2021,
    advantage: ["专精特新", "高新技术企业"],
    location: "上海市",
    media: false,
    hiring: true,
    recruitment: "社招",
    bestEmployer: true,
    desc: "ARM 架构高性能 CPU 芯片设计公司。团队来自 AMD/苹果/高通，专注 PC/服务器 CPU，国产替代明星。",
    fundingAmt: "数亿元人民币",
    investors: "联想创投、蔚来资本、启明创投",
    employees: "200-500人",
    product: "Cix ARM CPU",
    cities: ["上海", "苏州", "硅谷"],
    techStack: ["C++", "SystemVerilog", "Python", "ARM架构", "EDA工具"],
    benefits: ["六险一金", "股票期权", "顶级实验室", "论文发表"],
    website: "https://www.cixtech.com",
    jobs: [
      { title: "SoC设计工程师", salary: "40-70K", exp: "3-5年", degree: "本科" },
      { title: "芯片验证工程师", salary: "35-60K", exp: "3-5年", degree: "本科" },
      { title: "Linux内核工程师", salary: "30-50K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 工具软件 =====
  {
    id: 16,
    name: "白描 (Baimiao)",
    industry: "工具软件",
    funding: "未融资",
    year: 2018,
    advantage: [],
    location: "北京市",
    media: false,
    hiring: false,
    recruitment: "社招",
    bestEmployer: true,
    desc: "高精度 OCR 文字识别工具，个人开发者作品。App Store 效率榜常年前列，小而美的标杆产品。",
    fundingAmt: "未融资",
    investors: "个人独立开发",
    employees: "1-5人",
    product: "白描OCR",
    cities: ["北京"],
    techStack: ["Swift", "Kotlin", "Python", "CoreML"],
    benefits: ["独立开发", "远程", "收入分成"],
    website: "https://baimiaoapp.com",
    jobs: []
    ]
  },

  // ===== 能源环保 =====
  {
    id: 17,
    name: "正泰新能 (Astronergy)",
    industry: "能源环保",
    funding: "已上市",
    year: 2006,
    advantage: ["高新技术企业"],
    location: "浙江省",
    media: true,
    hiring: true,
    recruitment: "社招",
    bestEmployer: true,
    desc: "正泰集团旗下光伏制造，全球光伏组件出货量 Top 10。从硅片到组件全产业链布局，海外市场增长强劲。",
    fundingAmt: "上市公司",
    investors: "正泰集团",
    employees: "10000+",
    product: "Astronergy光伏组件",
    cities: ["温州", "杭州", "海宁"],
    techStack: ["PLC", "SCADA", "Python", "MES"],
    benefits: ["五险一金", "员工宿舍", "餐补", "班车"],
    website: "https://www.astronergy.com",
    jobs: [
      { title: "工艺工程师", salary: "15-25K", exp: "1-3年", degree: "本科" },
      { title: "海外销售经理", salary: "20-35K", exp: "3-5年", degree: "本科" },
      { title: "设备工程师", salary: "12-22K", exp: "1-3年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 社交网络 =====
  {
    id: 18,
    name: "Soul App",
    industry: "社交网络",
    funding: "D轮",
    year: 2016,
    advantage: ["独角兽"],
    location: "上海市",
    media: true,
    hiring: true,
    recruitment: "社招",
    bestEmployer: true,
    desc: "新一代社交平台，基于兴趣图谱和 AI 匹配。年轻用户占比极高，已提交港交所上市申请。",
    fundingAmt: "超2亿美元",
    investors: "腾讯、米哈游、元生资本",
    employees: "1000-2000人",
    product: "Soul App",
    cities: ["上海", "北京"],
    techStack: ["Java", "Go", "Python", "Flink", "TensorFlow"],
    benefits: ["六险一金", "16薪", "免费三餐", "健身房"],
    website: "https://www.soulapp.cn",
    jobs: [
      { title: "推荐算法工程师", salary: "35-60K", exp: "3-5年", degree: "本科" },
      { title: "Android开发", salary: "28-48K", exp: "3-5年", degree: "本科" },
      { title: "数据分析师", salary: "20-38K", exp: "2-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 物联网/硬件 =====
  {
    id: 19,
    name: "涂鸦智能 (Tuya)",
    industry: "物联网/硬件",
    funding: "已上市",
    year: 2014,
    advantage: ["高新技术企业"],
    location: "浙江省",
    media: true,
    hiring: true,
    recruitment: "社招",
    bestEmployer: true,
    desc: "全球化 IoT 云平台，已在美国纽交所上市。连接全球超 200 个国家和地区，AI+IoT 开发者生态庞大。",
    fundingAmt: "纽交所上市",
    investors: "NEA、腾讯",
    employees: "3000+",
    product: "Tuya IoT云平台",
    cities: ["杭州", "深圳", "硅谷"],
    techStack: ["Java", "Go", "C", "嵌入式", "K8s"],
    benefits: ["六险一金", "股票", "海外轮岗", "技术大会"],
    website: "https://www.tuya.com",
    jobs: [
      { title: "嵌入式开发", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "Java后端架构师", salary: "35-55K", exp: "5-10年", degree: "本科" },
      { title: "海外产品经理", salary: "25-40K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 物流 =====
  {
    id: 20,
    name: "箱信科技",
    industry: "物流",
    funding: "A+轮",
    year: 2019,
    advantage: ["创新型中小企业"],
    location: "天津市",
    media: false,
    hiring: false,
    recruitment: "社招",
    bestEmployer: true,
    desc: "集装箱运输智能调度平台。用算法匹配货主与货车，提升集装箱运输效率。港口物流数字化新锐。",
    fundingAmt: "千万级人民币",
    investors: "真格基金、源码资本",
    employees: "50-150人",
    product: "箱信智能调度",
    cities: ["天津"],
    techStack: ["Java", "Python", "Vue", "PostgreSQL"],
    benefits: ["五险一金", "弹性工作"],
    website: "https://www.xiangxin.tech",
    jobs: [
      { title: "Java后端开发", salary: "18-30K", exp: "2-5年", degree: "本科" },
      { title: "算法工程师", salary: "25-40K", exp: "2-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 第二批：更多隐形好公司 =====

  // ===== 先进制造 =====
  {
    id: 21,
    name: "优必选 (UBTECH)",
    industry: "先进制造",
    funding: "已上市",
    year: 2012,
    advantage: ["独角兽","高新技术企业"],
    location: "广东省",
    media: true,
    hiring: true,
    recruitment: "校招",
    bestEmployer: true,
    desc: "人形机器人第一股（港股上市），Walker系列人形机器人全球领先。教育/物流/康养多场景落地，研发团队超千人。",
    fundingAmt: "港股IPO",
    investors: "腾讯、启明创投、科大讯飞",
    employees: "2000+",
    product: "Walker人形机器人",
    cities: ["深圳", "北京", "洛杉矶"],
    techStack: ["C++", "Python", "ROS", "SLAM", "TensorFlow"],
    benefits: ["六险一金", "股票期权", "人才房", "海外展会"],
    website: "https://www.ubtrobot.com",
    jobs: [
      { title: "运动控制算法工程师", salary: "35-60K", exp: "3-5年", degree: "本科" },
      { title: "SLAM算法工程师", salary: "30-55K", exp: "2-5年", degree: "本科" },
      { title: "嵌入式软件工程师", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },
  {
    id: 22,
    name: "节卡机器人 (JAKA)",
    industry: "先进制造",
    funding: "D轮",
    year: 2014,
    advantage: ["专精特新小巨人","独角兽"],
    location: "上海市",
    media: true,
    hiring: true,
    recruitment: "校招",
    bestEmployer: true,
    desc: "协作机器人龙头，已获丰田、比亚迪等头部客户。全球协作机器人出货量前三，柔性制造场景王者。",
    fundingAmt: "超10亿人民币",
    investors: "淡马锡、软银愿景基金、比亚迪",
    employees: "500-1000人",
    product: "JAKA协作机器人",
    cities: ["上海", "常州", "慕尼黑"],
    techStack: ["C++", "Python", "ROS2", "EtherCAT", "Qt"],
    benefits: ["六险一金", "项目奖金", "海外培训", "落户支持"],
    website: "https://www.jakarobotics.com",
    jobs: [
      { title: "机器人控制算法", salary: "35-55K", exp: "3-5年", degree: "本科" },
      { title: "C++开发工程师", salary: "28-45K", exp: "3-5年", degree: "本科" },
      { title: "海外技术支持", salary: "20-35K", exp: "2-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 医疗健康 =====
  {
    id: 23,
    name: "晶泰科技 (XtalPi)",
    industry: "医疗健康",
    funding: "D轮",
    year: 2015,
    advantage: ["独角兽","高新技术企业"],
    location: "广东省",
    media: true,
    hiring: true,
    recruitment: "校招",
    bestEmployer: true,
    desc: "AI 药物研发头部玩家，量子物理+AI+云计算驱动新药发现。与辉瑞等国际药企合作，技术壁垒极高。",
    fundingAmt: "超7亿美元",
    investors: "红杉中国、腾讯、谷歌、软银",
    employees: "1000+",
    product: "XtalPi AI制药平台",
    cities: ["深圳", "北京", "波士顿"],
    techStack: ["Python", "PyTorch", "量子化学", "云计算", "K8s"],
    benefits: ["六险一金", "股票期权", "国际会议", "Nature发论文"],
    website: "https://www.xtalpi.com",
    jobs: [
      { title: "计算化学研究员", salary: "40-70K", exp: "博士", degree: "本科" },
      { title: "AI算法工程师", salary: "35-60K", exp: "3-5年", degree: "本科" },
      { title: "Python后端开发", salary: "28-48K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },
  {
    id: 24,
    name: "数坤科技 (Shukun)",
    industry: "医疗健康",
    funding: "C+轮",
    year: 2017,
    advantage: ["专精特新","高新技术企业"],
    location: "北京市",
    media: true,
    hiring: true,
    recruitment: "校招",
    bestEmployer: true,
    desc: "AI 辅助诊断冠脉/头颈/胸部疾病，已获 NMPA 多张三类证。覆盖全国 2000+ 医院，心脑血管 AI 赛道第一。",
    fundingAmt: "数亿元人民币",
    investors: "红杉中国、华盖资本、远毅资本",
    employees: "300-500人",
    product: "Shukun AI诊断",
    cities: ["北京", "上海"],
    techStack: ["Python", "PyTorch", "C++", "CUDA", "DICOM"],
    benefits: ["六险一金", "落户指标", "科研经费", "医学培训"],
    website: "https://www.shukun.net",
    jobs: [
      { title: "医学图像算法", salary: "30-50K", exp: "2-5年", degree: "本科" },
      { title: "Java后端开发", salary: "25-40K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "22-38K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 企业服务 =====
  {
    id: 25,
    name: "ONES",
    industry: "企业服务",
    funding: "C轮",
    year: 2015,
    advantage: ["高新技术企业","瞪羚企业"],
    location: "广东省",
    media: true,
    hiring: true,
    recruitment: "社招",
    bestEmployer: true,
    desc: "企业级研发管理工具（对标 Jira），已服务小米、浪潮、招商局等。国内研发管理 SaaS 领军， Atlassian 中国替代首选。",
    fundingAmt: "超1亿美元",
    investors: "XVC、顺为资本、源码资本",
    employees: "300-500人",
    product: "ONES研发管理",
    cities: ["深圳", "广州"],
    techStack: ["Go", "React", "TypeScript", "PostgreSQL", "K8s"],
    benefits: ["六险一金", "Mac办公", "年度旅游", "技术书籍"],
    website: "https://ones.ai",
    jobs: [
      { title: "前端架构师", salary: "35-55K", exp: "5-10年", degree: "本科" },
      { title: "Go后端开发", salary: "30-50K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "28-45K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },
  {
    id: 26,
    name: "分贝通 (Fenbeitong)",
    industry: "企业服务",
    funding: "C+轮",
    year: 2016,
    advantage: ["瞪羚企业","高新技术企业"],
    location: "北京市",
    media: true,
    hiring: true,
    recruitment: "社招",
    bestEmployer: true,
    desc: "企业支出管理平台，整合商旅/采购/费控/支付。已服务数千家中大型企业，新一代企业支付赛道头部。",
    fundingAmt: "超10亿人民币",
    investors: "高瓴创投、腾讯、IDG资本",
    employees: "500-1000人",
    product: "分贝通企业支出",
    cities: ["北京", "上海", "深圳"],
    techStack: ["Java", "Spring Cloud", "React", "Flink", "K8s"],
    benefits: ["六险一金", "补充医疗", "弹性工作", "期权"],
    website: "https://www.fenbeitong.com",
    jobs: [
      { title: "Java架构师", salary: "35-55K", exp: "5-10年", degree: "本科" },
      { title: "前端开发", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "测试开发", salary: "22-38K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 通信/半导体 =====
  {
    id: 27,
    name: "长鑫存储 (CXMT)",
    industry: "通信/半导体",
    funding: "战略融资",
    year: 2016,
    advantage: ["独角兽","高新技术企业"],
    location: "安徽省",
    media: true,
    hiring: true,
    recruitment: "校招",
    bestEmployer: true,
    desc: "中国唯一量产 DRAM 的 IDM 企业。国产存储芯片突破者，国家大基金重注，半导体国产替代核心标的。",
    fundingAmt: "超300亿人民币",
    investors: "大基金二期、合肥产投、兆易创新",
    employees: "5000+",
    product: "CXMT DRAM芯片",
    cities: ["合肥"],
    techStack: ["C++", "Verilog", "Python", "半导体工艺", "EDA"],
    benefits: ["六险一金", "人才公寓", "高额公积金", "安家费"],
    website: "https://www.cxmt.com",
    jobs: [
      { title: "IC设计工程师", salary: "40-70K", exp: "3-5年", degree: "本科" },
      { title: "工艺整合工程师", salary: "30-50K", exp: "3-5年", degree: "本科" },
      { title: "设备工程师", salary: "20-35K", exp: "2-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },
  {
    id: 28,
    name: "瀚博半导体 (Vastai)",
    industry: "通信/半导体",
    funding: "B+轮",
    year: 2020,
    advantage: ["专精特新"],
    location: "上海市",
    media: false,
    hiring: true,
    recruitment: "社招",
    bestEmployer: true,
    desc: "高性能 AI 推理芯片，自研通用 GPU 架构。创始人来自 AMD 全球副总裁，芯片已量产落地。国产 GPU 替代潜力股。",
    fundingAmt: "数亿元人民币",
    investors: "经纬创投、红点中国、五源资本",
    employees: "200-500人",
    product: "Vastai AI推理GPU",
    cities: ["上海", "硅谷"],
    techStack: ["C++", "CUDA", "SystemVerilog", "Python", "LLVM"],
    benefits: ["六险一金", "股票期权", "硅谷轮岗", "顶级GPU资源"],
    website: "https://www.vastaitech.com",
    jobs: [
      { title: "GPU架构工程师", salary: "50-80K", exp: "5-10年", degree: "本科" },
      { title: "AI编译器开发", salary: "40-65K", exp: "3-5年", degree: "本科" },
      { title: "驱动开发工程师", salary: "30-50K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 文化娱乐 =====
  {
    id: 29,
    name: "原力动画 (Original Force)",
    industry: "文化娱乐",
    funding: "战略融资",
    year: 2010,
    advantage: ["高新技术企业"],
    location: "江苏省",
    media: false,
    hiring: true,
    recruitment: "社招",
    bestEmployer: true,
    desc: "国内顶级 3D 动画制作公司，参与《凡人修仙传》《遮天》等顶级国漫制作。与 Netflix、腾讯视频深度合作，动画工业化标杆。",
    fundingAmt: "数亿元人民币",
    investors: "腾讯、B站、乐游资本",
    employees: "500-1000人",
    product: "原力3D动画",
    cities: ["南京", "上海"],
    techStack: ["C++", "Python", "Unreal", "Maya", "Houdini"],
    benefits: ["六险一金", "项目奖金", "创意自由", "行业顶级项目"],
    website: "https://www.of3d.com",
    jobs: [
      { title: "UE5引擎开发", salary: "25-40K", exp: "2-5年", degree: "本科" },
      { title: "3D动画师", salary: "18-30K", exp: "1-3年", degree: "本科" },
      { title: "技术美术(TA)", salary: "25-45K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 教育 =====
  {
    id: 30,
    name: "火花思维 (Spark Education)",
    industry: "教育",
    funding: "E轮",
    year: 2017,
    advantage: ["独角兽"],
    location: "北京市",
    media: true,
    hiring: true,
    recruitment: "校招",
    bestEmployer: true,
    desc: "在线素质教育平台，数理思维赛道头号玩家。双减后转型素质教育成功，海外业务增速迅猛。",
    fundingAmt: "超5亿美元",
    investors: "红杉中国、KKR、GGV、快手",
    employees: "3000+",
    product: "火花思维在线教育",
    cities: ["北京", "成都", "武汉"],
    techStack: ["Java", "Go", "React", "Flink", "AI"],
    benefits: ["六险一金", "子女免费课程", "弹性工作"],
    website: "https://www.huohua.cn",
    jobs: [
      { title: "后端架构师", salary: "35-55K", exp: "5-10年", degree: "本科" },
      { title: "数据工程师", salary: "28-48K", exp: "3-5年", degree: "本科" },
      { title: "AI课程设计师", salary: "20-35K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 消费电商 =====
  {
    id: 31,
    name: "徕芬 (Laifen)",
    industry: "消费电商",
    funding: "B轮",
    year: 2019,
    advantage: ["瞪羚企业"],
    location: "广东省",
    media: true,
    hiring: true,
    recruitment: "社招",
    bestEmployer: true,
    desc: "高速吹风机/电动牙刷新国货，用技术降维打击戴森。年营收超 20 亿，产品力极强，出海势头凶猛。",
    fundingAmt: "数亿元人民币",
    investors: "大钲资本、顺为资本",
    employees: "500-1000人",
    product: "徕芬高速吹风机",
    cities: ["深圳", "东莞"],
    techStack: ["C", "嵌入式", "SolidWorks", "Python"],
    benefits: ["五险一金", "产品内购", "年终分红"],
    website: "https://www.laifentech.com",
    jobs: [
      { title: "嵌入式开发", salary: "28-45K", exp: "3-5年", degree: "本科" },
      { title: "电商运营总监", salary: "30-50K", exp: "5-10年", degree: "本科" },
      { title: "工业设计", salary: "22-38K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 能源环保 =====
  {
    id: 32,
    name: "蜂巢能源 (SVOLT)",
    industry: "能源环保",
    funding: "Pre-IPO",
    year: 2018,
    advantage: ["独角兽","高新技术企业"],
    location: "江苏省",
    media: true,
    hiring: true,
    recruitment: "校招",
    bestEmployer: true,
    desc: "长城汽车孵化，动力电池 Top 10。短刀电池技术路线独树一帜，已建多个百GWh基地，科创板冲刺中。",
    fundingAmt: "超200亿人民币",
    investors: "IDG资本、国家绿色发展基金、碧桂园创投",
    employees: "10000+",
    product: "蜂巢短刀电池",
    cities: ["常州", "南京", "湖州", "遂宁"],
    techStack: ["Python", "MATLAB", "PLC", "MES", "C++"],
    benefits: ["六险一金", "人才公寓", "餐补", "班车", "年终奖"],
    website: "https://www.svolt.cn",
    jobs: [
      { title: "电池研发工程师", salary: "25-45K", exp: "2-5年", degree: "本科" },
      { title: "工艺工程师", salary: "18-30K", exp: "1-3年", degree: "本科" },
      { title: "MES开发工程师", salary: "20-35K", exp: "2-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 金融 =====
  {
    id: 33,
    name: "同盾科技 (Tongdun)",
    industry: "金融",
    funding: "D轮",
    year: 2013,
    advantage: ["专精特新","高新技术企业"],
    location: "浙江省",
    media: true,
    hiring: true,
    recruitment: "校招",
    bestEmployer: true,
    desc: "智能风控与决策分析，服务超万家金融机构和企业。从反欺诈到信用评估，金融科技基础设施级公司。",
    fundingAmt: "超20亿人民币",
    investors: "中投公司、招商局资本、宽带资本",
    employees: "1000-2000人",
    product: "同盾智能风控",
    cities: ["杭州", "北京", "上海"],
    techStack: ["Java", "Python", "Spark", "Flink", "TensorFlow"],
    benefits: ["六险一金", "股票期权", "技术大会", "论文激励"],
    website: "https://www.tongdun.cn",
    jobs: [
      { title: "风控算法工程师", salary: "30-50K", exp: "3-5年", degree: "本科" },
      { title: "Java开发", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "数据分析师", salary: "20-35K", exp: "2-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 汽车出行 =====
  {
    id: 34,
    name: "经纬恒润 (HiRain)",
    industry: "汽车出行",
    funding: "已上市",
    year: 2003,
    advantage: ["高新技术企业"],
    location: "北京市",
    media: true,
    hiring: true,
    recruitment: "校招",
    bestEmployer: true,
    desc: "汽车电子龙头，ADAS/智能驾驶域控制器头部供应商。服务国内外主流车企，智能汽车 Tier1 国产替代标杆。",
    fundingAmt: "科创板上市",
    investors: "一汽、上汽、广汽",
    employees: "5000+",
    product: "HiRain汽车电子",
    cities: ["北京", "天津", "上海", "长春"],
    techStack: ["C", "嵌入式", "AUTOSAR", "MATLAB", "Python"],
    benefits: ["六险一金", "人才引进落户", "购车优惠", "项目奖金"],
    website: "https://www.hirain.com",
    jobs: [
      { title: "自动驾驶算法", salary: "35-60K", exp: "3-5年", degree: "本科" },
      { title: "嵌入式开发", salary: "25-42K", exp: "2-5年", degree: "本科" },
      { title: "系统工程师", salary: "22-38K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 广告营销 =====
  {
    id: 35,
    name: "特赞 (Tezign)",
    industry: "广告营销",
    funding: "D轮",
    year: 2015,
    advantage: ["高新技术企业","瞪羚企业"],
    location: "上海市",
    media: true,
    hiring: true,
    recruitment: "社招",
    bestEmployer: true,
    desc: "内容科技独角兽，用 AI 管理品牌内容资产。服务阿里、联合利华等 200+ 品牌，Martech 赛道头部。",
    fundingAmt: "超10亿人民币",
    investors: "淡马锡、红杉中国、赫斯特资本",
    employees: "300-500人",
    product: "特赞内容科技",
    cities: ["上海", "北京"],
    techStack: ["Python", "Go", "React", "TensorFlow", "K8s"],
    benefits: ["六险一金", "弹性工作", "创意氛围", "行业峰会"],
    website: "https://www.tezign.com",
    jobs: [
      { title: "AI算法工程师", salary: "35-55K", exp: "3-5年", degree: "本科" },
      { title: "前端开发", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "25-40K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 物联网/硬件 =====
  {
    id: 36,
    name: "绿米联创 (Aqara)",
    industry: "物联网/硬件",
    funding: "C+轮",
    year: 2009,
    advantage: ["专精特新","高新技术企业"],
    location: "广东省",
    media: true,
    hiring: true,
    recruitment: "校招",
    bestEmployer: true,
    desc: "全屋智能家居龙头，小米生态链标杆企业。Zigbee/Thread/Matter 多协议，产品销往 190+ 国家。",
    fundingAmt: "超10亿人民币",
    investors: "顺为资本、凯辉基金、远翼投资",
    employees: "1000+",
    product: "Aqara全屋智能",
    cities: ["深圳", "广州", "硅谷"],
    techStack: ["C", "Zigbee", "嵌入式Linux", "Go", "React"],
    benefits: ["六险一金", "智能家居免费体验", "海外机会"],
    website: "https://www.aqara.com",
    jobs: [
      { title: "嵌入式开发", salary: "25-40K", exp: "3-5年", degree: "本科" },
      { title: "IoT平台开发", salary: "28-45K", exp: "3-5年", degree: "本科" },
      { title: "海外产品经理", salary: "22-38K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 物流 =====
  {
    id: 37,
    name: "极智嘉 (Geek+)",
    industry: "物流",
    funding: "E轮",
    year: 2015,
    advantage: ["独角兽","专精特新小巨人"],
    location: "北京市",
    media: true,
    hiring: true,
    recruitment: "校招",
    bestEmployer: true,
    desc: "全球 AMR 自主移动机器人市占率第一。仓储物流机器人出货超万台，海外营收占比超 50%。",
    fundingAmt: "超8亿美元",
    investors: "GGV、华平投资、英特尔资本",
    employees: "1500+",
    product: "Geek+仓储机器人",
    cities: ["北京", "上海", "香港", "东京", "法兰克福"],
    techStack: ["C++", "Python", "ROS", "SLAM", "多智能体"],
    benefits: ["六险一金", "股票期权", "海外轮岗", "机器人随便玩"],
    website: "https://www.geekplus.com",
    jobs: [
      { title: "路径规划算法", salary: "35-60K", exp: "3-5年", degree: "本科" },
      { title: "C++开发", salary: "28-48K", exp: "3-5年", degree: "本科" },
      { title: "海外项目经理", salary: "25-40K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 区块链 =====
  {
    id: 38,
    name: "比特大陆 (Bitmain)",
    industry: "区块链",
    funding: "战略融资",
    year: 2013,
    advantage: ["独角兽","高新技术企业"],
    location: "北京市",
    media: true,
    hiring: true,
    recruitment: "校招",
    bestEmployer: true,
    desc: "全球最大加密货币矿机厂商，ASIC 芯片设计能力全球顶级。旗下蚂蚁矿机市占率超 70%，AI 芯片新方向拓展中。",
    fundingAmt: "超10亿美元",
    investors: "红杉中国、IDG资本、GIC",
    employees: "1000+",
    product: "蚂蚁矿机",
    cities: ["北京", "深圳", "新加坡"],
    techStack: ["C++", "Verilog", "Python", "CUDA", "芯片设计"],
    benefits: ["六险一金", "项目分红", "顶级芯片工艺", "海外机会"],
    website: "https://www.bitmain.com",
    jobs: [
      { title: "芯片设计工程师", salary: "45-75K", exp: "3-5年", degree: "本科" },
      { title: "AI编译器开发", salary: "35-60K", exp: "3-5年", degree: "本科" },
      { title: "全栈工程师", salary: "30-50K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 传统制造（高端化） =====
  {
    id: 39,
    name: "思谋科技 (SmartMore)",
    industry: "传统制造",
    funding: "B+轮",
    year: 2019,
    advantage: ["独角兽","高新技术企业"],
    location: "广东省",
    media: true,
    hiring: true,
    recruitment: "校招",
    bestEmployer: true,
    desc: "AI 视觉赋能智能制造，贾佳亚教授（原腾讯优图）创立。已落地 1000+ 工业视觉场景，精密制造 AI 检测王者。",
    fundingAmt: "超3亿美元",
    investors: "IDG资本、联想创投、基石资本",
    employees: "500-1000人",
    product: "SmartMore AI质检",
    cities: ["深圳", "香港", "新加坡"],
    techStack: ["C++", "Python", "OpenCV", "CUDA", "PyTorch"],
    benefits: ["六险一金", "股票期权", "顶级CV团队", "论文发表"],
    website: "https://www.smartmore.com",
    jobs: [
      { title: "计算机视觉算法", salary: "40-65K", exp: "3-5年", degree: "本科" },
      { title: "C++开发工程师", salary: "30-50K", exp: "3-5年", degree: "本科" },
      { title: "解决方案架构师", salary: "28-45K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  },

  // ===== 文化娱乐（二次元） =====
  {
    id: 40,
    name: "叠纸游戏 (Papergames)",
    industry: "文化娱乐",
    funding: "战略融资",
    year: 2013,
    advantage: ["独角兽"],
    location: "上海市",
    media: true,
    hiring: true,
    recruitment: "校招",
    bestEmployer: true,
    desc: "女性向游戏绝对王者，《恋与制作人》《闪耀暖暖》等现象级产品。研发实力强，IP 衍生品和海外市场表现优异。",
    fundingAmt: "数亿美元",
    investors: "腾讯、字节跳动（已退出）",
    employees: "1000-2000人",
    product: "恋与制作人 / 闪耀暖暖",
    cities: ["上海"],
    techStack: ["C++", "Unity", "Python", "Go", "Unreal"],
    benefits: ["六险一金", "16薪", "项目分红", "二次元天堂"],
    website: "https://www.papegames.com",
    jobs: [
      { title: "Unity开发", salary: "28-48K", exp: "3-5年", degree: "本科" },
      { title: "游戏服务器开发", salary: "28-45K", exp: "3-5年", degree: "本科" },
      { title: "3D角色美术", salary: "22-38K", exp: "3-5年", degree: "本科" },
      { title: "产品经理", salary: "25-42K", exp: "3-5年", degree: "本科" },
      { title: "前端开发工程师", salary: "22-40K", exp: "2-5年", degree: "本科" },
    ]
  }
];

// Filter option definitions
const FILTERS = {
  industry: ["不限","文化娱乐","消费电商","汽车出行","教育","金融","企业服务","产业升级","前沿技术","医疗健康","先进制造","通信/半导体","物联网/硬件","工具软件","社交网络","农林牧渔","能源环保","本地生活","体育游戏","跨境出海","房产地产","旅游","广告营销","智能硬件","物流","区块链","传统制造","元宇宙","其他"],
  funding: ["不限","未融资","种子轮","天使轮","Pre-A轮","A轮","A+轮","Pre-B轮","B轮","B+轮","C轮","C+轮","D轮","D+轮","E轮","F轮","G轮","H轮","股权融资","战略融资","定向增发","Pre-IPO","基石轮","已上市","IPO","新三板","已退市/私有化","并购/合并","其他"],
  year: ["不限","2026年","2025年","2024年","2023年","2022年","2021年","2020年","2019年","2018年","2017年","2016年","2015年","2014年","2013年","2012年","2011年","2010年及以前"],
  advantage: ["不限","专精特新小巨人","专精特新","创新型中小企业","高新技术企业","科技型中小企业","独角兽","瞪羚企业","雏鹰企业"],
  location: ["不限","中国","海外","福建省","广东省","北京市","香港特别行政区","吉林省","天津市","辽宁省","上海市","河北省","江苏省","内蒙古自治区","台湾省","贵州省","宁夏回族自治区","浙江省","安徽省","山东省","黑龙江省","山西省","陕西省","广西壮族自治区","河南省","重庆市","四川省","云南省","澳门特别行政区","湖北省","西藏自治区","甘肃省","海南省","新疆维吾尔自治区","青海省","湖南省","江西省"],
  media: ["不限","是","否"],
  hiring: ["不限","是","否"],
  recruitment: ["不限","社招","校招"],
  bestEmployer: ["不限","是","否"],
  degree: ["不限","大专","本科","硕士","博士"]
};
